#!/usr/bin/env python3
"""Rank tiles for manual mask refinement.

The ranking combines:
- Classification uncertainty (binary entropy from legacy classifier probability)
- CAM uncertainty near mask boundaries (high means harder/ambiguous masks)
- Sparsity prior on positive-mask ratio (prefer plausible thin-structure density)
- Structural prior from retained components
- Diversity prior by mapsheet to avoid oversampling one area

Input is the CAM manifest generated by scripts/generate_gradcam_otsu_masks.py.
Output is a ranked CSV that can be consumed by scripts/brush_mask_labeler.py --tile-csv.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import math
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import cv2
import numpy as np

try:
    import torch
except Exception:  # pragma: no cover - optional fallback
    torch = None

try:
    import rasterio
    from rasterio.windows import Window
except Exception:  # pragma: no cover - optional fallback
    rasterio = None
    Window = None

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

_MAP_YEAR_RE = re.compile(r"(?P<mapsheet>\d{6})_(?P<year>\d{4})")


@dataclass
class Candidate:
    tile_id: str
    sample_id: str
    mapsheet: str
    year: str
    raster_path: Optional[Path]
    row_off: Optional[int]
    col_off: Optional[int]
    chunk_size: Optional[int]
    mask_file: str
    cam_file: str
    mask_path: Path
    cam_path: Path
    otsu_threshold: float
    mask_positive_ratio: float
    cam_mean: float
    components_total: float
    components_kept: float
    legacy_prob: Optional[float] = None
    entropy: float = 0.0
    border_uncertainty: float = 0.0
    ratio_score: float = 0.0
    structure_score: float = 0.0
    cam_uncertainty: float = 0.0
    base_score: float = 0.0
    diversity_prior: float = 1.0
    rank_score: float = 0.0


def _safe_float(value: str, default: float = 0.0) -> float:
    try:
        return float(str(value).strip())
    except Exception:
        return float(default)


def _safe_int(value: str, default: Optional[int] = None) -> Optional[int]:
    try:
        return int(str(value).strip())
    except Exception:
        return default


def _entropy_score(p: float) -> float:
    p = max(1e-9, min(1.0 - 1e-9, float(p)))
    return -(p * math.log2(p) + (1.0 - p) * math.log2(1.0 - p))


def _extract_positive_score(logits):
    if torch is None:
        raise RuntimeError("torch is required to extract classifier probabilities")
    if logits.ndim == 2 and logits.shape[1] >= 2:
        return torch.softmax(logits, dim=1)[:, 1]
    if logits.ndim == 2 and logits.shape[1] == 1:
        return torch.sigmoid(logits[:, 0])
    if logits.ndim == 1:
        return torch.sigmoid(logits)
    return torch.sigmoid(logits.view(logits.shape[0], -1).mean(dim=1))


def _gaussian_center_score(value: float, center: float, sigma: float) -> float:
    sigma_safe = max(1e-6, float(sigma))
    z = (float(value) - float(center)) / sigma_safe
    return float(math.exp(-0.5 * z * z))


def _resolve_path(raw_path: str, base_dirs: list[Path]) -> Path:
    p = Path(str(raw_path).strip())
    if p.is_absolute():
        return p
    for base in base_dirs:
        cand = (base / p).resolve()
        if cand.exists():
            return cand
    return (base_dirs[0] / p).resolve()


def _parse_tile_id(tile_id: str) -> tuple[str, Optional[str], Optional[int], Optional[int]]:
    parts = str(tile_id).strip().split(":")
    if len(parts) >= 4:
        sample_id = parts[0]
        variant = parts[1].strip().lower()
        row_off = _safe_int(parts[-2])
        col_off = _safe_int(parts[-1])
        return sample_id, variant, row_off, col_off
    sample_id = parts[0] if parts else ""
    return sample_id, None, None, None


def _infer_mapsheet_year(sample_id: str) -> tuple[str, str]:
    m = _MAP_YEAR_RE.search(str(sample_id))
    if not m:
        return "", ""
    return str(m.group("mapsheet")), str(m.group("year"))


def _extract_sample_id_from_raster_stem(stem: str, variant: str) -> Optional[str]:
    marker = f"_harmonized_dem_last_{variant}_chm"
    if marker in stem:
        return stem.split(marker, 1)[0]

    marker_alt = f"_{variant}_chm"
    if marker_alt in stem:
        return stem.split(marker_alt, 1)[0]

    return None


def _build_raster_lookup(data_dir: Path) -> dict[tuple[str, str], Path]:
    lookup: dict[tuple[str, str], Path] = {}

    for variant in ("raw", "gauss"):
        variant_dir = data_dir / f"chm_{variant}"
        if not variant_dir.exists():
            continue
        for tif_path in sorted(variant_dir.glob("*.tif")):
            sample_id = _extract_sample_id_from_raster_stem(tif_path.stem, variant)
            if not sample_id:
                continue
            lookup[(sample_id, variant)] = tif_path.resolve()

    if lookup:
        return lookup

    # Fallback for alternative layouts: recursively scan data_dir.
    for tif_path in sorted(data_dir.rglob("*.tif")):
        stem = tif_path.stem
        for variant in ("raw", "gauss"):
            sample_id = _extract_sample_id_from_raster_stem(stem, variant)
            if sample_id:
                lookup[(sample_id, variant)] = tif_path.resolve()
                break

    return lookup


def _load_candidates(manifest_csv: Path, cam_mask_dir: Path) -> list[Candidate]:
    candidates: list[Candidate] = []

    with manifest_csv.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            tile_id = str(row.get("tile_id", "")).strip()
            if not tile_id:
                continue

            mask_file = str(row.get("mask_file", "")).strip()
            cam_file = str(row.get("cam_file", "")).strip()
            if not mask_file or not cam_file:
                continue

            mask_path = _resolve_path(mask_file, [cam_mask_dir, manifest_csv.parent])
            cam_path = _resolve_path(cam_file, [cam_mask_dir, manifest_csv.parent])
            if not mask_path.exists() or not cam_path.exists():
                continue

            raster_raw = str(row.get("raster_path", "")).strip()
            raster_path = _resolve_path(raster_raw, [manifest_csv.parent, cam_mask_dir]) if raster_raw else None

            cand = Candidate(
                tile_id=tile_id,
                sample_id=str(row.get("sample_id", "")).strip(),
                mapsheet=str(row.get("mapsheet", "")).strip(),
                year=str(row.get("year", "")).strip(),
                raster_path=raster_path,
                row_off=_safe_int(str(row.get("row_off", "")).strip()),
                col_off=_safe_int(str(row.get("col_off", "")).strip()),
                chunk_size=_safe_int(str(row.get("chunk_size", "")).strip()),
                mask_file=mask_file,
                cam_file=cam_file,
                mask_path=mask_path,
                cam_path=cam_path,
                otsu_threshold=_safe_float(str(row.get("otsu_threshold", "")), default=0.5),
                mask_positive_ratio=_safe_float(str(row.get("mask_positive_ratio", "")), default=0.0),
                cam_mean=_safe_float(str(row.get("cam_mean", "")), default=0.0),
                components_total=_safe_float(str(row.get("components_total", "")), default=0.0),
                components_kept=_safe_float(str(row.get("components_kept", "")), default=0.0),
            )
            candidates.append(cand)

    return candidates


def _resolve_missing_raster_info(candidates: list[Candidate], lookup: dict[tuple[str, str], Path]) -> int:
    resolved = 0
    for cand in candidates:
        was_complete = (
            cand.raster_path is not None
            and cand.row_off is not None
            and cand.col_off is not None
            and cand.chunk_size is not None
        )

        parsed_sample, parsed_variant, parsed_row, parsed_col = _parse_tile_id(cand.tile_id)
        if not cand.sample_id and parsed_sample:
            cand.sample_id = parsed_sample
        if cand.row_off is None and parsed_row is not None:
            cand.row_off = int(parsed_row)
        if cand.col_off is None and parsed_col is not None:
            cand.col_off = int(parsed_col)
        if cand.chunk_size is None:
            cand.chunk_size = 128

        if not cand.mapsheet or not cand.year:
            mapsheet, year = _infer_mapsheet_year(cand.sample_id)
            if not cand.mapsheet and mapsheet:
                cand.mapsheet = mapsheet
            if not cand.year and year:
                cand.year = year

        if cand.raster_path is None:
            raster = None
            if cand.sample_id and parsed_variant:
                raster = lookup.get((cand.sample_id, parsed_variant))
            if raster is None and cand.sample_id:
                raster = lookup.get((cand.sample_id, "raw")) or lookup.get((cand.sample_id, "gauss"))
            if raster is not None:
                cand.raster_path = raster

        now_complete = (
            cand.raster_path is not None
            and cand.row_off is not None
            and cand.col_off is not None
            and cand.chunk_size is not None
        )
        if now_complete and not was_complete:
            resolved += 1

    return resolved


def _read_tile_from_raster(
    cand: Candidate,
    handles: dict[str, object],
) -> Optional[np.ndarray]:
    if rasterio is None or Window is None:
        return None
    if cand.raster_path is None:
        return None
    if cand.row_off is None or cand.col_off is None or cand.chunk_size is None:
        return None
    if not cand.raster_path.exists():
        return None

    key = str(cand.raster_path)
    src = handles.get(key)
    if src is None:
        src = rasterio.open(cand.raster_path)
        handles[key] = src

    win = Window(int(cand.col_off), int(cand.row_off), int(cand.chunk_size), int(cand.chunk_size))
    arr = src.read(1, window=win, boundless=True, fill_value=0).astype(np.float32)
    return np.nan_to_num(arr, nan=0.0, posinf=0.0, neginf=0.0).astype(np.float32)


def _compute_legacy_probabilities(
    candidates: list[Candidate],
    *,
    model,
    device,
    batch_size: int,
) -> int:
    if model is None or torch is None:
        for cand in candidates:
            cand.legacy_prob = None
        return 0

    handles: dict[str, object] = {}
    assigned = 0

    try:
        model.eval()
        for start in range(0, len(candidates), max(1, int(batch_size))):
            end = min(len(candidates), start + max(1, int(batch_size)))
            arrs: list[np.ndarray] = []
            indices: list[int] = []

            for idx in range(start, end):
                cand = candidates[idx]
                tile = _read_tile_from_raster(cand, handles)
                if tile is None:
                    continue
                tile_small = cv2.resize(tile, (128, 128), interpolation=cv2.INTER_LINEAR)
                arrs.append(tile_small.astype(np.float32))
                indices.append(idx)

            if not arrs:
                continue

            x_np = np.stack(arrs, axis=0).astype(np.float32)
            x = torch.from_numpy(x_np).unsqueeze(1).to(device)
            x = torch.clamp(x, 0.0, 20.0) / 20.0

            with torch.no_grad():
                logits = model(x)
                probs = _extract_positive_score(logits).detach().cpu().numpy().astype(np.float32)

            for idx, prob in zip(indices, probs):
                candidates[idx].legacy_prob = float(np.clip(prob, 0.0, 1.0))
                assigned += 1
    finally:
        for src in handles.values():
            try:
                src.close()
            except Exception:
                pass

    return assigned


def _compute_border_uncertainty(cam_path: Path, mask_path: Path) -> float:
    cam = np.asarray(np.load(cam_path, allow_pickle=False), dtype=np.float32)
    mask = np.asarray(np.load(mask_path, allow_pickle=False), dtype=np.float32)

    cam = np.squeeze(cam)
    mask = np.squeeze(mask)
    if cam.ndim != 2:
        cam = cam.reshape(cam.shape[-2], cam.shape[-1])
    if mask.ndim != 2:
        mask = mask.reshape(mask.shape[-2], mask.shape[-1])

    if cam.shape != mask.shape:
        cam = cv2.resize(cam, (mask.shape[1], mask.shape[0]), interpolation=cv2.INTER_LINEAR)

    cam = np.clip(cam, 0.0, 1.0).astype(np.float32)
    mask_bin = (mask >= 0.5).astype(np.uint8)

    kernel = np.ones((3, 3), dtype=np.uint8)
    boundary = cv2.morphologyEx(mask_bin, cv2.MORPH_GRADIENT, kernel) > 0

    uncertainty = 1.0 - np.abs((2.0 * cam) - 1.0)
    if np.any(boundary):
        return float(np.mean(uncertainty[boundary]))

    inside = mask_bin > 0
    if np.any(inside):
        return float(np.mean(uncertainty[inside]))

    return float(np.mean(uncertainty))


def main() -> None:
    parser = argparse.ArgumentParser(description="Rank tiles for manual brush-mask labeling")
    parser.add_argument("--manifest-csv", type=str, required=True, help="Input CAM manifest.csv")
    parser.add_argument("--output-csv", type=str, required=True, help="Output ranked CSV")
    parser.add_argument("--cam-mask-dir", type=str, default="", help="Base directory for manifest mask/cam files")

    parser.add_argument("--legacy-checkpoint", type=str, default="", help="Optional classifier checkpoint for entropy ranking")
    parser.add_argument("--device", type=str, default="", help="Device override (cuda/cpu)")
    parser.add_argument("--batch-size", type=int, default=64)

    parser.add_argument("--prefilter-k", type=int, default=4000, help="Cheap prefilter before expensive features (0=all)")
    parser.add_argument("--top-k", type=int, default=1000, help="Number of rows to write (0=all)")
    parser.add_argument("--max-per-mapsheet", type=int, default=0, help="Optional cap per mapsheet after ranking")

    parser.add_argument("--target-positive-ratio", type=float, default=0.05)
    parser.add_argument("--ratio-sigma", type=float, default=0.04)
    parser.add_argument("--diversity-exp", type=float, default=0.5, help="Mapsheet diversity exponent")

    parser.add_argument("--w-entropy", type=float, default=0.45)
    parser.add_argument("--w-border", type=float, default=0.25)
    parser.add_argument("--w-ratio", type=float, default=0.15)
    parser.add_argument("--w-structure", type=float, default=0.10)
    parser.add_argument("--w-cam-unc", type=float, default=0.05)

    parser.add_argument("--data-dir", type=str, default="", help="Optional: data-dir to recover raster metadata")
    parser.add_argument(
        "--registry-dir",
        type=str,
        default="",
        help="Backward-compatible no-op (kept for older command lines)",
    )
    parser.add_argument("--split", type=str, default="all", choices=["train", "val", "test", "trainval", "all"])
    parser.add_argument("--max-tiles-per-raster", type=int, default=2500)
    parser.add_argument("--test-size", type=float, default=0.2)
    parser.add_argument("--val-size", type=float, default=0.1)
    parser.add_argument("--buffer-meters", type=float, default=50.0)
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
    )

    manifest_csv = Path(args.manifest_csv)
    if not manifest_csv.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_csv}")

    cam_mask_dir = Path(args.cam_mask_dir) if str(args.cam_mask_dir).strip() else manifest_csv.parent
    output_csv = Path(args.output_csv)
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    candidates = _load_candidates(manifest_csv=manifest_csv, cam_mask_dir=cam_mask_dir)
    if not candidates:
        raise RuntimeError("No valid candidates loaded from manifest")
    total_loaded = len(candidates)

    logging.info("Loaded %d candidates from manifest", len(candidates))

    lookup: dict[tuple[str, str], Path] = {}
    missing_raster_before = sum(
        1
        for c in candidates
        if c.raster_path is None or c.row_off is None or c.col_off is None or c.chunk_size is None
    )

    if missing_raster_before > 0 and args.data_dir:
        logging.info("Resolving missing raster metadata via data-dir raster lookup...")
        lookup = _build_raster_lookup(Path(args.data_dir))
        logging.info("Indexed %d raster(s) from data-dir", len(lookup))
        resolved = _resolve_missing_raster_info(candidates, lookup)
        logging.info("Resolved raster metadata for %d candidate(s)", resolved)

    for cand in candidates:
        cand.ratio_score = _gaussian_center_score(
            cand.mask_positive_ratio,
            center=float(args.target_positive_ratio),
            sigma=float(args.ratio_sigma),
        )
        if cand.components_total > 0.0:
            cand.structure_score = float(np.clip(cand.components_kept / max(1.0, cand.components_total), 0.0, 1.0))
        else:
            cand.structure_score = 0.5
        cand.cam_uncertainty = float(np.clip(1.0 - abs((2.0 * cand.cam_mean) - 1.0), 0.0, 1.0))

    if int(args.prefilter_k) > 0 and len(candidates) > int(args.prefilter_k):
        def _prefilter_score(c: Candidate) -> float:
            return (0.45 * c.cam_uncertainty) + (0.35 * c.ratio_score) + (0.20 * c.structure_score)

        candidates.sort(key=_prefilter_score, reverse=True)
        candidates = candidates[: int(args.prefilter_k)]
        logging.info("Prefiltered to %d candidates", len(candidates))

    prefiltered_count = len(candidates)

    model = None
    device_name = args.device if args.device else ("cuda" if (torch is not None and torch.cuda.is_available()) else "cpu")
    device = torch.device(device_name) if torch is not None else device_name
    if args.legacy_checkpoint and torch is not None:
        try:
            from cdw_detect.cwd_partialconv_pipeline import load_legacy_model

            model = load_legacy_model(args.legacy_checkpoint, device=device)
            if model is None:
                logging.warning("Failed to load legacy checkpoint, continuing without classifier entropy")
        except Exception as exc:
            logging.warning("Legacy model loader unavailable (%s), continuing without classifier entropy", exc)
    elif args.legacy_checkpoint and torch is None:
        logging.warning("torch unavailable: ignoring --legacy-checkpoint and using non-classifier ranking")

    assigned_probs = _compute_legacy_probabilities(
        candidates,
        model=model,
        device=device,
        batch_size=int(args.batch_size),
    )
    logging.info("Computed classifier probabilities for %d candidate(s)", assigned_probs)

    for cand in candidates:
        if cand.legacy_prob is None:
            cand.entropy = cand.cam_uncertainty
        else:
            cand.entropy = _entropy_score(cand.legacy_prob)

    for idx, cand in enumerate(candidates, start=1):
        try:
            cand.border_uncertainty = _compute_border_uncertainty(cand.cam_path, cand.mask_path)
        except Exception as exc:
            cand.border_uncertainty = cand.cam_uncertainty
            if idx <= 10:
                logging.warning("Border uncertainty fallback for %s (%s)", cand.tile_id, exc)

    mapsheet_counts: dict[str, int] = {}
    for cand in candidates:
        key = cand.mapsheet if cand.mapsheet else "unknown"
        mapsheet_counts[key] = mapsheet_counts.get(key, 0) + 1

    for cand in candidates:
        cand.base_score = (
            float(args.w_entropy) * cand.entropy
            + float(args.w_border) * cand.border_uncertainty
            + float(args.w_ratio) * cand.ratio_score
            + float(args.w_structure) * cand.structure_score
            + float(args.w_cam_unc) * cand.cam_uncertainty
        )

        ms_key = cand.mapsheet if cand.mapsheet else "unknown"
        freq = max(1, mapsheet_counts.get(ms_key, 1))
        cand.diversity_prior = 1.0 / (float(freq) ** float(max(0.0, args.diversity_exp)))
        cand.rank_score = cand.base_score * cand.diversity_prior

    candidates.sort(key=lambda c: c.rank_score, reverse=True)

    selected: list[Candidate] = []
    per_mapsheet: dict[str, int] = {}
    cap = int(max(0, args.max_per_mapsheet))
    top_k = int(max(0, args.top_k))

    for cand in candidates:
        ms_key = cand.mapsheet if cand.mapsheet else "unknown"
        if cap > 0 and per_mapsheet.get(ms_key, 0) >= cap:
            continue
        selected.append(cand)
        per_mapsheet[ms_key] = per_mapsheet.get(ms_key, 0) + 1
        if top_k > 0 and len(selected) >= top_k:
            break

    logging.info("Selected %d ranked candidates", len(selected))

    with output_csv.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=[
                "rank",
                "rank_score",
                "base_score",
                "diversity_prior",
                "tile_id",
                "sample_id",
                "mapsheet",
                "year",
                "raster_path",
                "row_off",
                "col_off",
                "chunk_size",
                "legacy_prob",
                "legacy_entropy",
                "border_uncertainty",
                "ratio_score",
                "structure_score",
                "cam_uncertainty",
                "cam_mean",
                "mask_positive_ratio",
                "components_total",
                "components_kept",
                "mask_file",
                "cam_file",
                "mask_path",
                "cam_path",
            ],
        )
        writer.writeheader()

        for rank, cand in enumerate(selected, start=1):
            writer.writerow(
                {
                    "rank": rank,
                    "rank_score": f"{cand.rank_score:.6f}",
                    "base_score": f"{cand.base_score:.6f}",
                    "diversity_prior": f"{cand.diversity_prior:.6f}",
                    "tile_id": cand.tile_id,
                    "sample_id": cand.sample_id,
                    "mapsheet": cand.mapsheet,
                    "year": cand.year,
                    "raster_path": str(cand.raster_path) if cand.raster_path is not None else "",
                    "row_off": "" if cand.row_off is None else int(cand.row_off),
                    "col_off": "" if cand.col_off is None else int(cand.col_off),
                    "chunk_size": "" if cand.chunk_size is None else int(cand.chunk_size),
                    "legacy_prob": "" if cand.legacy_prob is None else f"{cand.legacy_prob:.6f}",
                    "legacy_entropy": f"{cand.entropy:.6f}",
                    "border_uncertainty": f"{cand.border_uncertainty:.6f}",
                    "ratio_score": f"{cand.ratio_score:.6f}",
                    "structure_score": f"{cand.structure_score:.6f}",
                    "cam_uncertainty": f"{cand.cam_uncertainty:.6f}",
                    "cam_mean": f"{cand.cam_mean:.6f}",
                    "mask_positive_ratio": f"{cand.mask_positive_ratio:.6f}",
                    "components_total": f"{cand.components_total:.3f}",
                    "components_kept": f"{cand.components_kept:.3f}",
                    "mask_file": cand.mask_file,
                    "cam_file": cand.cam_file,
                    "mask_path": str(cand.mask_path),
                    "cam_path": str(cand.cam_path),
                }
            )

    summary = {
        "manifest_csv": str(manifest_csv),
        "output_csv": str(output_csv),
        "input_candidates": int(total_loaded),
        "prefiltered_candidates": int(prefiltered_count),
        "selected_candidates": len(selected),
        "assigned_classifier_probs": int(assigned_probs),
        "used_classifier_entropy": bool(model is not None and assigned_probs > 0),
        "prefilter_k": int(args.prefilter_k),
        "top_k": int(args.top_k),
        "max_per_mapsheet": int(args.max_per_mapsheet),
        "weights": {
            "w_entropy": float(args.w_entropy),
            "w_border": float(args.w_border),
            "w_ratio": float(args.w_ratio),
            "w_structure": float(args.w_structure),
            "w_cam_unc": float(args.w_cam_unc),
        },
        "diversity_exp": float(args.diversity_exp),
        "target_positive_ratio": float(args.target_positive_ratio),
        "ratio_sigma": float(args.ratio_sigma),
    }
    summary_path = output_csv.with_suffix(".summary.json")
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    logging.info("Wrote ranked CSV: %s", output_csv)
    logging.info("Wrote summary: %s", summary_path)


if __name__ == "__main__":
    main()
